### PR TITLE
Updated samples to work with dotnet core 2.1 and on any OS including …

### PR DESCRIPTION
**Pull request by evermeire**
The .DrawText along a path method has changed and I am not sure how to get that sample to actually render text along a path.  Currently, it renders the path, but the text is rendered in a straight line at a specific point.

### CODE REVIEW

**Comment by 2E0PGS** [comment]
Looks good to me!

**Comment by evermeire** [comment]
I signed the CLA.

**Comment by JimBobSquarePants** [comment]
Thanks @evermeire 👍 

Some of this work already exists in #4 We need to merge that first then rebase your PR.

**Comment by tocsoft** [comment]
thanks @evermeire for this PR these changes have already been made as part of other PRs etc so i'll just close this now as its no longer required.

**Pull request closed without merging**
